### ISSUE TITLE
Feature request: Add a command to select emoji only

### ISSUE THREAD

**Issue by jdanbrown** [brunnerh/insert-unicode#43]
Love this extension! It's always a pain to have to dig through google when I need some unicode symbols, and this extension does a great job letting me sift through unicode quickly. It's also very helpful that you've added recents and favorites, for quick recall of frequently used characters.

One feature request: add an insert command for emoji only, without all the rest of unicode
- e.g. when I do `Insert` and type `arrow` to try to find the emoji arrows (e.g. ⬆️⬇️⬅️➡️), I have to scroll through many pages of unicode arrows before I get down to the emoji arrows

This unicode extension has better usability than the rest of the emoji extensions I've found in the marketplace (because it has recents, favorites, data table, etc.), and if it had a command to filter to emoji only then I think it'd be the best one for the very common case of selecting emoji, in addition to also being able to select unicode

**Comment by brunnerh** [comment]
There are new commands in v.0.15.0:
- *Insert Emoji* (`insert-unicode.insertEmojiText`)
- *Insert Emoji as Decimal Code* (`insert-unicode.insertEmojiDecimalCode`)
- *Insert Emoji as Hex Code* (`insert-unicode.insertEmojiHexCode`)

**Comment by jdanbrown** [comment]
Awesome, thank you! 🎉

**Comment by jdanbrown** [comment]
Hmm, is the emoji filter working correctly? When I use "Insert Emoji" I do get many fewer characters, but I still get some non-emoji characters:
- "Insert" → search for "arrow" → lots of unicode characters with no emoji results near the top (expected)
- "Insert Emoji" → search for "arrow" → emoji results are now visible (expected), but still a small set of non-emoji results too (not expected)

| Insert | Insert Emoji |
|---|---|
| <img width="597" alt="image" src="https://github.com/brunnerh/insert-unicode/assets/627486/3ee1897f-3e9d-4f64-85ad-2aeef8440c83"> | <img width="605" alt="image" src="https://github.com/brunnerh/insert-unicode/assets/627486/b576da17-19ea-4b2e-a801-a6e98435d216"> |

**Comment by brunnerh** [comment]
Those are all part of the Emoji standard.

Things like the selection of emoji you see in messengers or OS provided pickers are probably hand selected because as you noticed, there are many. What renders as a fancy image is up to the font.

Unfortunately this is probably the only reasonable reduction I can do on my end without using some unofficial and thus arbitrary listing. If there are commonly used lists available, maybe a setting could be added which controls the Emoji commands, so the default value would be `"standard"` and other named sets could be selected as well.

**Comment by brunnerh** [comment]
I guess there is one wrinkle that could be adjusted still: Some Emoji have a "fully-qualified" and "unqualified" version, and the former is supposed to be displayed as a picture rather than a plain icon. The "unqualified" versions could be filtered out, though that still is no guarantee for pretty pictures as that depends on the font's completeness.

E.g. not all arrows implement the picture version in my default Windows font:
![image](https://github.com/brunnerh/insert-unicode/assets/834235/5a885e67-fc8e-44f9-8a45-c3746750742a)

**Comment by brunnerh** [comment]
List is now reduced to this:
![image](https://github.com/brunnerh/insert-unicode/assets/834235/0b5938c4-0b83-49e1-b968-2984ff225541)

**Comment by jdanbrown** [comment]
Works great, thank you x2!
