### ISSUE TITLE
how to type a unicode character in VS Code

### ISSUE THREAD

**Issue by bortval** [brunnerh/insert-unicode#7]
I would like to know how to type a unicode character in VS Code directly without an extension

**Comment by brunnerh** [comment]
@bortval Well, that depends on the operating system. In Windows 10, for example, there is an Emoji picker which can be opened with Windows+Period(.). Alternatively if you know the code you can hold Alt and enter the code sequence on the number pad.

**Comment by bortval** [comment]
I'd like to know combinations of keys for writing unicode characters in Visual Studio Code in Windows 10 with the codes in unicode. Alt+code sequence only works for ASCII characters.

**Comment by brunnerh** [comment]
@bortval 
1. I have written non-ASCII characters that way.
2. Why exactly are you asking me about this? I am neither support for Windows, nor VS Code. This extension exists precisely to make that easier. Why do you think it exists?

**Comment by David263** [comment]
I'm with bortval. If you're going to offer a Unicode extension, you should know how your tools already work and support your users. I'm interested in the same question. I don't just want to pick emoji or look on a Unicode website to find an interesting character, I want to use and support Unicode in my application code. That is the only reason I am abandoning a wonderful editor called NoteTab: because is cannot handle Unicode. I can't find any way to view Unicode code points in hexadecimal in VSCode, which is otherwise laden with features.

**Comment by brunnerh** [comment]
@David263 You are asking about the extension; this is not. I will get back to you...

**Comment by patfinder** [comment]
Use Wordpad (Alt-Numpad [method](https://en.wikipedia.org/wiki/Unicode_input#Decimal_input_(Alt_codes))), then copy the character to VSCode. See my guide [here](https://dev.to/patfinder/keyboard-ancient-secrets-5g7k).
Or use a plugin, properly [this one](https://marketplace.visualstudio.com/items?itemName=brunnerh.insert-unicode).

**Comment by Welding-Torch** [comment]
@patfinder That's not a useable solution for someone who wants to use lots of Unicode chars everyday.

**Comment by patfinder** [comment]
> @patfinder That's not a useable solution for someone who wants to use lots of Unicode chars everyday.

Or use a plugin, properly [this one](https://marketplace.visualstudio.com/items?itemName=brunnerh.insert-unicode).
