### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by David263** [brunnerh/insert-unicode#9]
So I installed this extension in VSCode, but can't find a scrap of documentation in its writeup or in VSCode menus. What does this extension actually do? What keystrokes or commands does it add? Where is its documentation and why is it hidden there?

Okay, I just found the instructions: in the README of this repository. Yes, I call this 'hidden'.

And I can't use the confusing video showing someone typing into VSCode. Videos don't help: (1) they go by too fast, (2) you can't tell what the user is typing vs. what the product is responding with, (3) there are no actual detailed explanations of what is happening in the video.

Also, the README instructions are confusing. They seem to provide snippets of JSON to link commands to keystrokes. Are we supposed to enter these into the Settings JSON if we want to actually use this extension? It is okay if we are, I just want to see instructions that actually say that.

I count three snippets. Does this extension consist only in those three commands, or is there more? The instructions don't make this clear.

It says "This command will show the Unicode name and code point of the selected characters."

Sounds useful. What does it mean by "this command"? Is it the previous command, insert-unicode.insertFont, or some other?

An extension can't be used by everyone without clear instructions.

**Comment by brunnerh** [comment]
The Read-Me states in the very first sentence:

> This is an extension for Visual Studio Code which **adds commands** for inserting Unicode characters/codes and Emoji.

That is all it does, and i expected users to know how to execute commands as it is one of the most basic interactions in VS Code (`View > Command Palette...` or by default Ctrl+Shift+P). I can add more clarification though for future readers.

The Read-Me is what also shows up in the marketplace of the extension, it is not hidden by any means. Also, all the question about what the extension adds can be answered in the marketplace/VS Code when selecting the extension.

Note the `Contributions` tab right under the flame icon:

![image](https://user-images.githubusercontent.com/834235/65275979-1ee45a00-db27-11e9-85d4-4eac95417cf3.png)

If you click it, you will see this:

![image](https://user-images.githubusercontent.com/834235/65276021-34598400-db27-11e9-98d3-2aa10eccecd6.png)

The JSON bit in the Read-Me shows how to create custom key bindings with arguments. You don't have to set up key bindings and can run them from the command palette. The UI for configuring key bindings does not allow setting arguments, so i showed an example how to do it in the JSON file. I do not pre-set any key bindings, because i want to leave it up the user.

"this command" at that point refers to the sub-heading `Identify Unicode Characters` which states the name of the command i am explaining. All the sub-headings refer to a command or a group of commands. Again, i could add more info to clarify that...

**Comment by brunnerh** [comment]
Updated Read-Me with v.0.7.0.

**Comment by MisinformedDNA** [comment]
I'm with @David263. I don't get it.

1. Select Insert option
![image](https://user-images.githubusercontent.com/1784452/70457322-90bca780-1a75-11ea-8a3f-fca1426a5161.png)

2.  Get prompt
![image](https://user-images.githubusercontent.com/1784452/70457268-784c8d00-1a75-11ea-93cd-b0f9489ce065.png)

3. Enter example text and there are no search results
![image](https://user-images.githubusercontent.com/1784452/70457755-556ea880-1a76-11ea-8e81-b9935ab12d60.png)

4. Press Enter and there are no search results
![image](https://user-images.githubusercontent.com/1784452/70457841-7df6a280-1a76-11ea-919b-afd068368bd2.png)

5. Type something else and there are still no search results
![image](https://user-images.githubusercontent.com/1784452/70458037-e47bc080-1a76-11ea-9770-76010b384765.png)

I can't get the extension to do anything!
